#!/usr/bin/env bash -l
echo "WARNING!: Proceeding will trust *everything* installed inside of your \$HOMEBREW_PREFIX, this is extremely dangerous!"
read -p "Are you sure you wish to procede? (y/N) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
  find $HOMEBREW_PREFIX/Cellar -type f -print0 | while IFS='' read -d '' line ; do
    if [[ -x "$line" ]]; then
      codesign --sign --force - "$line"
    fi
  done
  find $HOMEBREW_PREFIX/Caskroom -maxdepth 3 -name '*.app' -type d -print0 | while IFS='' read -d '' line ; do
    codesign --sign --deep --force - "$line"
  done
fi
