#!/usr/bin/env bash
# Backup packages
echo "Backing up packages..."
brew bundle --global --all --force dump
(
	cd $HOMEBREW_PREFIX/etc
	if [ -d ./.git ] && [ -f ./homebrew/Brewfile ]; then
		git commit -m "modify packages" ./homebrew/Brewfile
    echo ""
	fi
)

# Backup files to iCloud
if [ -f $HOMEBREW_PREFIX/etc/homebrew/backupPaths.conf ]; then
  function deref () {
	  case $1 in
		  '~p/'*) echo "$HOMEBREW_PREFIX/${1#'~p/'}";; #Prefix
		  '~r/'*) echo "/${1#'~r/'}";; # Root
		  '~h/'*) echo "$HOME/${1#'~h/'}";; # Home
		  '~a/'*) echo "$HOME/Library/Application Support/${1#'~a/'}";; # App Data
		  '~s/'*) echo "$HOME/Library/Saved Application State/${1#'~s/'}";; # Saved State
	  esac
  }
  mkdir -p "$(dirname "$HOMEBREW_BACKUP_PATH")"

  argv=("${HOMEBREW_BACKUP_CMD:-"zip"}" "${HOMEBREW_BACKUP_CMD_ARGS:-"-rFSy"}")
  if [ -z $HOMEBREW_BACKUP_PATH_BACK ]; then
    argv+=("${HOMEBREW_BACKUP_PATH:-"$HOME/Documents/Backup.zip"}")
  fi
  while read path; do
    echo "Backing up path: $path ..."
    realPath="$(deref "$path")"
    argv+=("$realPath")
  done <<< "$(grep -v "^\s*[#;]" "$HOMEBREW_PREFIX/etc/homebrew/backupPaths.conf" | grep -v "^\s*$")"
  if ! [ -z $HOMEBREW_BACKUP_PATH_BACK ]; then
    argv+=("${HOMEBREW_BACKUP_PATH:-"$HOME/Documents/Backup.zip"}")
  fi

  echo "Writing backup..."
  eval ${argv[*]@Q}
fi
